### ISSUE TITLE
Simplify import structure for `resolve_robotics_uri` function

### ISSUE THREAD

**Issue by fl-ferr** [ami-iit/resolve-robotics-uri-py#2]
The current package organization needs the following import statement for using the `resolve_robotics_uri` function:

```python
from resolve_robotics_uri_py.resolve_robotics_uri_py import resolve_robotics_uri
```

In the interest of maintaining concise import statements, the idea is to include the following line within the `__init__.py` file, simplifying the package import process:

```python
from .resolve_robotics_uri_py import resolve_robotics_uri
```

This adjustment would allow to import the function using the following compact syntax:

```python
from resolve_robotics_uri_py import resolve_robotics_uri
```

**Comment by traversaro** [comment]
It make sense, the readme is broken without this! Can you open a PR? Thanks!
